---
name: Duryab
# an automatic trigger [deploayment], whenever change is pushed ot branch
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: echo "Say hello $USER"
      - name: ask
        run: echo "how are you "
  details:
    runs-on: ubuntu-latest
    steps:
      - name: show what is the veriosn of python and docker image
        run: docker --version && python --version
