name: Python Matrix Testing

on:
  workflow_dispatch: 


jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        python_version: ["3.9","3.10","3.11","3.12"]
        ubuntu-version: ["ubuntu-slim", " ubuntu-latest"]
    runs-on: ${{matrix.ubuntu-version}}
   
    steps:
      - name: checkout code
        uses: actions/checkout@v7
        
      - name: python setup for ${{matrix.python_version}}
        uses: actions/setup-python@v6 
        with:
          python-version: ${{matrix.python_version}}
          
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Display python version
        run: python --version
        
      - name: run test
        run: python -m pytest
        

    
